In [1]:
import os, math 
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split 
from sklearn.model_selection import GridSearchCV 
from sklearn.preprocessing import OneHotEncoder 
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier 
from sklearn import datasets
from IPython.display import display
import warnings
warnings.filterwarnings("ignore")
le = LabelEncoder()
seed = np.random.seed
hotone = OneHotEncoder()

In [2]:
# load the data
dt = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', header=None)
dt.columns = ['Sepal length', 'Sepal width', 'Petal length', 'Petal width', 'Class label']
X = dt[['Sepal length', 'Sepal width', 'Petal length', 'Petal width']].values
y1 = pd.factorize(dt['Class label'])[0]
y = y1.reshape(-1,1) 
hotone.fit(y)
y_encoded = hotone.transform(y).toarray()

# split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=0, stratify=y)

# define hyperparameters
mlp = MLPClassifier(alpha=0.1, hidden_layer_sizes=20, learning_rate_init=0.001, max_iter=1000, random_state=1, solver='sgd') 
mlp.out_activation = 'softmax'

# hyperparameters using GridSearchCV
parametry = {'learning_rate_init': [0.1, 0.01, 0.001], 
             'hidden_layer_sizes': [20, 40, 60, 80, 100], 
             'solver': ['adam', 'lbfgs', 'sgd']}

clf = GridSearchCV(mlp, parametry)
clf.fit(X, y)

print("Best params: " + str(clf.best_params_))

# best parameters train the model 
mlp = MLPClassifier(alpha=0.1, hidden_layer_sizes=clf.best_params_['hidden_layer_sizes'],
                    learning_rate_init=clf.best_params_['learning_rate_init'], 
                    max_iter=1000, random_state=1,
                    solver=clf.best_params_['solver'], verbose=10)
mlp.out_activation = 'softmax'
mlp.fit(x_train, y_train)

Best params: {'hidden_layer_sizes': 40, 'learning_rate_init': 0.01, 'solver': 'sgd'}
Iteration 1, loss = 3.68185464
Iteration 2, loss = 2.67188522
Iteration 3, loss = 2.03136814
Iteration 4, loss = 1.89461094
Iteration 5, loss = 1.90525861
Iteration 6, loss = 1.90464356
Iteration 7, loss = 1.86788883
Iteration 8, loss = 1.79970122
Iteration 9, loss = 1.72176130
Iteration 10, loss = 1.64803213
Iteration 11, loss = 1.57418842
Iteration 12, loss = 1.50164821
Iteration 13, loss = 1.43377378
Iteration 14, loss = 1.37506429
Iteration 15, loss = 1.32719922
Iteration 16, loss = 1.28950031
Iteration 17, loss = 1.25844905
Iteration 18, loss = 1.23075056
Iteration 19, loss = 1.20427253
Iteration 20, loss = 1.17873082
Iteration 21, loss = 1.15425075
Iteration 22, loss = 1.13018600
Iteration 23, loss = 1.10640511
Iteration 24, loss = 1.08311317
Iteration 25, loss = 1.06070037
Iteration 26, loss = 1.03960855
Iteration 27, loss = 1.02024886
Iteration 28, loss = 1.00328814
Iteration 29, loss = 0.98879

MLPClassifier(alpha=0.1, hidden_layer_sizes=40, learning_rate_init=0.01,
              max_iter=1000, random_state=1, solver='sgd', verbose=10)

In [3]:
# accuracy 
print("Accuracy (train): " + str(mlp.score(x_train, y_train)*100) + '%') 
print("Accuracy (test): "+ str(mlp.score(x_test, y_test)*100) + '%')

Accuracy (train): 97.5%
Accuracy (test): 100.0%


In [4]:
# confusion matrices 
Y_pred_train = mlp.predict(x_train)
print(confusion_matrix(y_train.argmax(axis=1),Y_pred_train.argmax(axis=1)))
Y_pred_test = mlp.predict(x_test)
print(confusion_matrix(y_test.argmax(axis=1),Y_pred_test.argmax(axis=1)))

[[40  0  0]
 [ 0 38  2]
 [ 0  1 39]]
[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]


In [8]:
# load the data
numbers = datasets.load_digits()

y = numbers.target
X = numbers.images.reshape((len(numbers.images), -1))

X = hotone.fit_transform(X).toarray()

# split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0, stratify=y)

# define hyperparameters
mlp = MLPClassifier(alpha=0.1, hidden_layer_sizes=20, learning_rate_init=0.001, max_iter=1000, random_state=1, solver='sgd') 
mlp.out_activation = 'softmax'

# hyperparameters using GridSearchCV
parametry = {'learning_rate_init': [0.1, 0.01, 0.001], 
             'hidden_layer_sizes': [20, 40, 60, 80, 100], 
             'solver': ['adam', 'lbfgs', 'sgd']}

clf = GridSearchCV(mlp, parametry)
clf.fit(X, y)

print("Best params: " + str(clf.best_params_))

# best parameters train the model 
mlp = MLPClassifier(alpha=0.1, hidden_layer_sizes=clf.best_params_['hidden_layer_sizes'],
                    learning_rate_init=clf.best_params_['learning_rate_init'], 
                    max_iter=1000, random_state=1,
                    solver=clf.best_params_['solver'], verbose=10)
mlp.out_activation = 'softmax'
mlp.fit(x_train, y_train)

Best params: {'hidden_layer_sizes': 40, 'learning_rate_init': 0.1, 'solver': 'lbfgs'}


MLPClassifier(alpha=0.1, hidden_layer_sizes=40, learning_rate_init=0.1,
              max_iter=1000, random_state=1, solver='lbfgs', verbose=10)

In [9]:
# accuracy 
print("Accuracy (train): " + str(mlp.score(x_train, y_train)*100) + '%') 
print("Accuracy (test): "+ str(mlp.score(x_test, y_test)*100) + '%')

Accuracy (train): 100.0%
Accuracy (test): 94.72222222222221%


In [10]:
# confusion matrices 
Y_pred_train = mlp.predict(x_train) 
print(confusion_matrix(y_train,Y_pred_train)) 
Y_pred_test = mlp.predict(x_test) 
print(confusion_matrix(y_test,Y_pred_test))

[[142   0   0   0   0   0   0   0   0   0]
 [  0 146   0   0   0   0   0   0   0   0]
 [  0   0 142   0   0   0   0   0   0   0]
 [  0   0   0 146   0   0   0   0   0   0]
 [  0   0   0   0 145   0   0   0   0   0]
 [  0   0   0   0   0 145   0   0   0   0]
 [  0   0   0   0   0   0 145   0   0   0]
 [  0   0   0   0   0   0   0 143   0   0]
 [  0   0   0   0   0   0   0   0 139   0]
 [  0   0   0   0   0   0   0   0   0 144]]
[[35  0  0  0  1  0  0  0  0  0]
 [ 0 36  0  0  0  0  0  0  0  0]
 [ 0  1 34  0  0  0  0  0  0  0]
 [ 0  0  0 35  0  0  0  1  1  0]
 [ 0  1  0  0 32  1  0  0  2  0]
 [ 0  0  0  0  0 37  0  0  0  0]
 [ 0  1  0  0  0  0 35  0  0  0]
 [ 0  0  0  0  0  0  0 36  0  0]
 [ 0  1  0  1  0  0  0  1 31  1]
 [ 0  1  0  1  0  2  0  1  1 30]]


In [5]:
# load the data
dt = pd.read_csv('WineQT.csv')

X = dt.drop(columns=['quality'])
y = dt['quality']
y = le.fit_transform(y)

X = hotone.fit_transform(X).toarray()

# split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=1, stratify=y)

# define hyperparameters
mlp = MLPClassifier(alpha=0.1, hidden_layer_sizes=100, learning_rate_init=0.001, max_iter=6000, random_state=1, solver='sgd') 
mlp.out_activation = 'softmax'

# hyperparameters using GridSearchCV
parametry = {'learning_rate_init': [0.1, 0.01, 0.001], 
             'hidden_layer_sizes': [20, 40, 60, 80, 100], 
             'solver': ['adam', 'lbfgs', 'sgd']}

clf = GridSearchCV(mlp, parametry)
clf.fit(X, y)

print("Best params: " + str(clf.best_params_))

# best parameters train the model 
mlp = MLPClassifier(alpha=0.1, hidden_layer_sizes=clf.best_params_['hidden_layer_sizes'],
                    learning_rate_init=clf.best_params_['learning_rate_init'], 
                    max_iter=1000, random_state=1,
                    solver=clf.best_params_['solver'], verbose=10)
mlp.out_activation = 'softmax'
mlp.fit(x_train, y_train)



In [12]:
# accuracy 
print("Accuracy (train): " + str(mlp.score(x_train, y_train)*100) + '%') 
print("Accuracy (test): "+ str(mlp.score(x_test, y_test)*100) + '%')

Accuracy (train): 95.03891050583657%
Accuracy (test): 58.26086956521739%


In [13]:
# confusion matrices 
Y_pred_train = mlp.predict(x_train) 
print(confusion_matrix(y_train,Y_pred_train)) 
Y_pred_test = mlp.predict(x_test) 
print(confusion_matrix(y_test,Y_pred_test))

[[  0   0   3   2   0   0]
 [  0   0  14  16   0   0]
 [  0   0 434   0   0   0]
 [  0   0   1 415   0   0]
 [  0   0   0   1 128   0]
 [  0   0   3   7   4   0]]
[[ 0  0  0  1  0  0]
 [ 0  0  2  1  0  0]
 [ 0  0 31 18  0  0]
 [ 0  0 12 32  2  0]
 [ 0  0  1  9  4  0]
 [ 0  0  1  1  0  0]]
